name: Run Detok

on:  
  push:
    branches:
      - main  # Change this to your default branch if it's different
  pull_request:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  run-detok:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  
      - name: Install dependencies
        run: npm install
      - name: Run detok
        run: npm run detok
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Run detok and commit changes" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.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 }}@github.com/pspmanu123/cptr_detok.git HEAD:main
      
